### ISSUE TITLE
package.json: dotenv dependency missing

### ISSUE THREAD

**Issue by lkraav** [rmehtije/copyTestingApp#2]
```
$ [git:master] npm start

> copytesting@1.0.0 start /home/leho/Documents/markitekt/copytesting/copyTestingApp
> node server.js

internal/modules/cjs/loader.js:1032
  throw err;
  ^

Error: Cannot find module 'dotenv'
Require stack:
- /home/leho/Documents/markitekt/copytesting/copyTestingApp/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Module.require (internal/modules/cjs/loader.js:1089:19)
    at require (internal/modules/cjs/helpers.js:73:18)
    at Object.<anonymous> (/home/leho/Documents/markitekt/copytesting/copyTestingApp/server.js:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/leho/Documents/markitekt/copytesting/copyTestingApp/server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! copytesting@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the copytesting@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/leho/.npm/_logs/2020-06-29T12_20_35_047Z-debug.log
```

**Comment by rmehtije** [comment]
Dependencies are added to package.json file

**Comment by lkraav** [comment]
OK, but launch still fails, because there is no `.env` committed, nor are there instructions on what values are required in it.

```
leho@papaya copyTestingApp $ [git:master] npm start

> copytesting@1.0.0 start /home/leho/Documents/markitekt/copytesting/copyTestingApp
> node server.js

/home/leho/Documents/markitekt/copytesting/copyTestingApp/node_modules/mongoose/lib/connection.js:582
    throw new MongooseError('The `uri` parameter to `openUri()` must be a ' +
    ^

MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.Connection.openUri (/home/leho/Documents/markitekt/copytesting/copyTestingApp/node_modules/mongoose/lib/connection.js:582:11)
    at Mongoose.connect (/home/leho/Documents/markitekt/copytesting/copyTestingApp/node_modules/mongoose/lib/index.js:335:15)
    at Object.<anonymous> (/home/leho/Documents/markitekt/copytesting/copyTestingApp/server.js:7:10)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! copytesting@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the copytesting@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/leho/.npm/_logs/2020-06-30T09_49_24_181Z-debug.log
```

**Comment by rmehtije** [comment]
Yes, unfortionatly i seem to forgot to add .env-example file. Added.

**Comment by lkraav** [comment]
App seems to launch now.
