### ISSUE TITLE
uncaught exception: [object Object] cb=gapi.loaded_0

### ISSUE THREAD

**Issue by lkraav** [rmehtije/copyTestingApp#3]
```
13:34:39.836 uncaught exception: [object Object] cb=gapi.loaded_0:163:58
    Aj https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.OfYsKuVZ3qI.O/m=auth2/rt=j/sv=1/d=1/ed=1/am=wQE/rs=AGLTcCMVod3aO7ybjljp3cyn2IsEoP0pUg/cb=gapi.loaded_0:163
```

Failing to get by initial status check

![image](https://user-images.githubusercontent.com/147228/86116955-e9699580-bad6-11ea-811e-cbd84f71c32e.png)

**Comment by lkraav** [comment]
App log says

```
leho@papaya copyTestingApp $ [git:master+] npm start

> copytesting@1.0.0 start /home/leho/Documents/markitekt/copytesting/copyTestingApp
> node server.js

Listening on port 5000
MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at NativeConnection.Connection.openUri (/home/leho/Documents/markitekt/copytesting/copyTestingApp/node_modules/mongoose/lib/connection.js:830:32)
    at Mongoose.connect (/home/leho/Documents/markitekt/copytesting/copyTestingApp/node_modules/mongoose/lib/index.js:335:15)
    at Object.<anonymous> (/home/leho/Documents/markitekt/copytesting/copyTestingApp/server.js:7:10)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  reason: TopologyDescription {
    type: 'Single',
    setName: null,
    maxSetVersion: null,
    maxElectionId: null,
    servers: Map(1) { 'localhost:27017' => [ServerDescription] },
    stale: false,
    compatible: true,
    compatibilityError: null,
    logicalSessionTimeoutMinutes: null,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    commonWireVersion: null
  }
}
(node:305575) UnhandledPromiseRejectionWarning: MongooseServerSelectionError: connect ECONNREFUSED 127.0.0.1:27017
    at NativeConnection.Connection.openUri (/home/leho/Documents/markitekt/copytesting/copyTestingApp/node_modules/mongoose/lib/connection.js:830:32)
    at Mongoose.connect (/home/leho/Documents/markitekt/copytesting/copyTestingApp/node_modules/mongoose/lib/index.js:335:15)
    at Object.<anonymous> (/home/leho/Documents/markitekt/copytesting/copyTestingApp/server.js:7:10)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:305575) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:305575) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by rmehtije** [comment]
Do you have mongodb running on the default port of 27017?
Do you have username and password set ?

**Comment by lkraav** [comment]
Installation requirements aren't really explicitly clear from README. App should also handle key component failure more gracefully.

MongoDB is installed and running now, but issue subject error still persists.

App console is clear, so must be a Google API issue?

**Comment by rmehtije** [comment]
I will keep in mind your suggestions in next repositories.

This could be due to Google sign-in has trouble with your site if its url is a pure IP address. Try to link localhost to an IP address.

**Comment by lkraav** [comment]
Not sure how, but I'm seeing a more detailed error message today.

```
11:25:56.139 Uncaught 
{…}
​
details: "Not a valid origin for the client: http://localhost:3000 has not been whitelisted for client ID 56211615720-rbs6ru30hsiacbudo1tv4jgodnfstqgk.apps.googleusercontent.com. Please go to https://console.developers.google.com/ and whitelist this origin for your project's client ID."
​
error: "idpiframe_initialization_failed"
​
<prototype>: Object { … }
cb=gapi.loaded_0:163:58
```

**Comment by rmehtije** [comment]
I have added http://localhost:3000 to Authorized Javascript Origins.
Please clear your cache and try again.
